#!/bin/bash
# setup.sh — Install cc-tmux-menu
set -e

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

INSTALL_DIR="${HOME}/.local/bin"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/cc-tmux-menu"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo ""
echo -e "${BOLD}cc-tmux-menu${NC} — Interactive tmux session manager with AI previews"
echo ""

# === Check dependencies ===
echo -e "${BOLD}Checking dependencies...${NC}"
missing=()
for cmd in tmux; do
  if command -v "$cmd" &>/dev/null; then
    echo -e "  ${GREEN}✓${NC} $cmd"
  else
    echo -e "  ${RED}✗${NC} $cmd (required)"
    missing+=("$cmd")
  fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
  echo ""
  echo -e "${RED}Missing: ${missing[*]}${NC}"
  echo "Install them and try again."
  exit 1
fi

echo ""

# === Build or use pre-built binary ===
echo -e "${BOLD}Installing...${NC}"
mkdir -p "$INSTALL_DIR"

if [[ -f "$SCRIPT_DIR/cc-tmux-menu" ]]; then
  # Pre-built binary exists
  cp "$SCRIPT_DIR/cc-tmux-menu" "$INSTALL_DIR/cc-tmux-menu"
  chmod +x "$INSTALL_DIR/cc-tmux-menu"
  echo -e "  ${GREEN}✓${NC} Copied pre-built binary to ${CYAN}${INSTALL_DIR}/cc-tmux-menu${NC}"
elif command -v go &>/dev/null; then
  # Build from source
  echo -e "  Building from source..."
  (cd "$SCRIPT_DIR" && go build -o "$INSTALL_DIR/cc-tmux-menu" ./cmd/cc-tmux-menu)
  echo -e "  ${GREEN}✓${NC} Built and installed to ${CYAN}${INSTALL_DIR}/cc-tmux-menu${NC}"
else
  echo -e "  ${RED}✗${NC} No pre-built binary found and Go is not installed."
  echo "  Install Go (https://go.dev/dl/) or place a pre-built binary in this directory."
  exit 1
fi

if ! echo "$PATH" | tr ':' '\n' | grep -qx "$INSTALL_DIR"; then
  echo -e "  ${YELLOW}!${NC} ${INSTALL_DIR} is not in PATH. Add to your shell profile:"
  echo -e "    ${CYAN}export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
fi
echo ""

# === Configuration ===
echo -e "${BOLD}Configuration${NC}"
mkdir -p "$CONFIG_DIR"

existing_config=""
if [[ -f "$CONFIG_DIR/config.toml" ]]; then
  existing_config="$CONFIG_DIR/config.toml"
elif [[ -f "$CONFIG_DIR/config" ]]; then
  existing_config="$CONFIG_DIR/config"
fi

if [[ -n "$existing_config" ]]; then
  echo -e "  Config exists: ${CYAN}${existing_config}${NC}"
  read -p "  Overwrite? [y/N] " overwrite
  if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
    echo -e "  Keeping existing config.\n"
    echo -e "${GREEN}${BOLD}Done!${NC} Run ${CYAN}cc-tmux-menu${NC} to start."
    exit 0
  fi
  echo ""
fi

# OpenRouter API key
echo -e "  ${BOLD}OpenRouter API Key${NC} ${DIM}(for AI session summaries)${NC}"
echo -e "  Get one at: ${CYAN}https://openrouter.ai/keys${NC}"
echo -e "  Leave empty to skip — summaries will be disabled."
read -p "  API Key: " api_key
echo ""

# Model
default_model="google/gemini-2.0-flash-001"
echo -e "  ${BOLD}AI Model${NC} ${DIM}(for summaries, cheap & fast recommended)${NC}"
echo -e "  Default: ${CYAN}${default_model}${NC}"
read -p "  Model [${default_model}]: " model
model="${model:-$default_model}"
echo ""

# Work directory
echo -e "  ${BOLD}Work Directory${NC} ${DIM}(for new Claude Code sessions)${NC}"
read -p "  Directory [~]: " work_dir
work_dir="${work_dir:-~}"
echo ""

# Language
echo -e "  ${BOLD}Summary Language${NC} ${DIM}(en, zh-TW, ja, ko, ...)${NC}"
read -p "  Language [en]: " lang
lang="${lang:-en}"
echo ""

# Remote host
echo -e "  ${BOLD}Remote SSH Host${NC} ${DIM}(optional, adds SSH option to menu)${NC}"
read -p "  Host (empty to skip): " remote_host
remote_user=""
if [[ -n "$remote_host" ]]; then
  read -p "  User [$(whoami)]: " remote_user
  remote_user="${remote_user:-$(whoami)}"
fi
echo ""

# Write config (TOML format)
cat > "$CONFIG_DIR/config.toml" << EOF
# cc-tmux-menu configuration
# Generated by setup.sh on $(date +%Y-%m-%d)

openrouter_api_key = "${api_key}"
openrouter_model = "${model}"
work_dir = "${work_dir}"
summary_lang = "${lang}"
claude_cmd = "claude"
remote_host = "${remote_host}"
remote_user = "${remote_user}"
preview_cache_ttl = 1800
EOF

chmod 600 "$CONFIG_DIR/config.toml"
echo -e "  ${GREEN}✓${NC} Config saved to ${CYAN}${CONFIG_DIR}/config.toml${NC}"
echo ""

# === Shell integration ===
echo -e "${BOLD}Shell Integration${NC}"
echo "  Auto-launch cc-tmux-menu when you open a terminal?"
read -p "  Add to shell profile? [y/N] " add_shell

if [[ "$add_shell" == "y" || "$add_shell" == "Y" ]]; then
  shell_rc=""
  if [[ -f "$HOME/.zshrc" ]]; then
    shell_rc="$HOME/.zshrc"
  elif [[ -f "$HOME/.bashrc" ]]; then
    shell_rc="$HOME/.bashrc"
  fi

  if [[ -n "$shell_rc" ]]; then
    if ! grep -q 'cc-tmux-menu' "$shell_rc" 2>/dev/null; then
      cat >> "$shell_rc" << 'SHELL_RC'

# cc-tmux-menu: interactive tmux session manager
[[ -z "$TMUX" && -x "$HOME/.local/bin/cc-tmux-menu" ]] && "$HOME/.local/bin/cc-tmux-menu"
SHELL_RC
      echo -e "  ${GREEN}✓${NC} Added to ${CYAN}${shell_rc}${NC}"
    else
      echo -e "  ${YELLOW}!${NC} Already in ${shell_rc}"
    fi
  else
    echo -e "  ${YELLOW}!${NC} Shell profile not found. Add manually:"
    echo -e '    [[ -z "$TMUX" && -x "$HOME/.local/bin/cc-tmux-menu" ]] && "$HOME/.local/bin/cc-tmux-menu"'
  fi
fi

echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
echo -e "  Run:    ${CYAN}cc-tmux-menu${NC}"
echo -e "  Config: ${CYAN}${CONFIG_DIR}/config.toml${NC}"
echo ""
